# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Copy the service account key file into the container
COPY ./serviceAccountKey.json /app/serviceAccountKey.json

# Set environment variable for Google Cloud authentication
ENV GOOGLE_APPLICATION_CREDENTIALS="/app/serviceAccountKey.json"

# Copy the requirements file into the container
COPY requirements.txt .
# Install dependencies
RUN pip install -r requirements.txt

# Expose port 5000 (or the port your app runs on)
EXPOSE 5000

# Run the command to start the Flask app
CMD ["flask", "run", "--host=0.0.0.0"]